### PR TITLE
fix: Exit status code for fatal Webpack exceptions

### LINKED ISSUE #1744: Failed builds return Exit Code 0
### Discussed in https://github.com/preactjs/preact-cli/discussions/1743

<div type='discussions-op-text'>

<sup>Originally posted by **jasonhilldm** October  2, 2022</sup>
I am using CircleCI to deploy an app when changes are pushed to git. One of the steps is the command "npm run build" which in turn runs "preact build".

When there is an error with the build, I am seeing a "Build failed!" message in the CircleCI step but it also says "CircleCI received exit code 0" and so continues with the next step of the deployment.

Any ideas why CircleCI is receiving an exit code 0 from the build step even though it has failed?

I see a very old issue about this same problem but it was fixed: https://github.com/preactjs/preact-cli/issues/61</div>

### PR DESCRIPTION
**Pull request by rschristian**
**What kind of change does this PR introduce?**

bugfix

**Did you add tests for your changes?**

No

**Summary**

Closes #1744 

We don't correctly handle fatal Webpack exceptions at the moment; the `err` in the callback for `compiler.run()` relates to fatal Webpack exceptions, like configuration errors. When one is hit, we only reject the promise, which actually allows the build to "complete" with a status code of `0`. We instead want to exit immediately with a status code `1` (as that matches what we do for compilation errors).

**Does this PR introduce a breaking change?**

No

### CODE REVIEW

File: packages/cli/src/lib/webpack/run-webpack.js [hunk 1]
```diff
@@ -78,14 +78,14 @@ async function prodBuild(env) {
...
-			showStats(stats, true);
-
-			if (err || (stats && stats.hasErrors())) {
-				rej(`${red('\n\nBuild failed! \n\n')} ${err || ''}`);
+			if (err) {
+				error(err, 1);
 			}
 
+			showStats(stats, true);
+
```
Comment (rschristian) [inline packages/cli/src/lib/webpack/run-webpack.js:88]: `showStats()`, in production builds, will also immediately exit upon coming across any errors; as such, there's no reason to ever reject this promise as we've already exited.

File: .github/workflows/ci.yml [hunk 2]
```diff
@@ -16,6 +16,7 @@ jobs:
   test:
     name: Test
     runs-on: ubuntu-latest
+    timeout-minutes: 10
```
Comment (rschristian) [inline .github/workflows/ci.yml:19]: Unrelated, but for some (godforsaken reason), puppeteer randomly never exits on the CI. I've seen no pattern for this, just that it occurs.

GitHub's default is 360 minutes, or 6 hours, which we definitely don't need. I just caught a run still going after an hour and had to manually kill it. 10 minutes should be plenty of time.

**Comment by rschristian** [comment]
Ugh, this works but I don't love that we're mixing throwing & `process.exit()` to signify errors. For end users it probably doesn't make too much of a difference but it does make our test suite a bit of a headache.

File: packages/cli/package.json [hunk 3]
```diff
@@ -127,7 +127,7 @@
     "preact": "^10.5.13",
     "preact-render-to-string": "^5.1.19",
     "preact-router": "^3.0.1",
-    "puppeteer": "^9.1.1",
+    "puppeteer": "^13.7.0",
```
Comment (rschristian) [inline packages/cli/package.json:130]: This shouldn't be necessary, but our version of Puppeteer has turned *super* flakey recently. Granted it probably is a good few years old, so maybe that's unavoidable.
