### PR TITLE
Using same version of preact for pre-rendering

### LINKED ISSUE #795: Duplicate preact instance while prerendering breaking options
Ported over from: https://github.com/developit/preact-render-to-string/issues/86#issuecomment-492325953

**Do you want to request a _feature_ or report a _bug_?**

bug

**What is the current behaviour?**

Prerendering will throw an undefined error:

```txt
TypeError: Cannot read property '__H' of undefined
```

This is caused by loading multiple instances of preact which can't see each others `option`-hooks. There are a total of 2 instances at play:

1) included in the generated `ssr-bundle.js`
2) one inside `prerender.js`: https://github.com/developit/preact-cli/blob/bd464043dac8646183ed9a8cfab677778f73b4f7/packages/cli/lib/lib/webpack/prerender.js#L28

Both instances have their own `options` variable which ultimately leads to this error.

**If the current behaviour is a bug, please provide the steps to reproduce.**

```json
{
  "scripts": {
    "build": "preact build"
  },
  "devDependencies": {
    "preact-cli": "^3.0.0-rc.1",
    "preact-render-to-string": "^5.0.3"
  },
  "dependencies": {
    "preact": "^10.0.0-beta.1"
  }
}
```

```jsx
import { useState } from "preact/hooks";

export default () => {
  const [a, b] = useState("c");
  return <h1>Hello, World! {a}</h1>;
};
```

**What is the expected behaviour?**

It should not throw.

**Please mention other relevant information.**

- Node version: 11.7
- npm version 6.5.0
- Operating system: Linux Debian Sid
- CLI version: 3.0.0-rc.1
- Browser: doesn't matter

### PR DESCRIPTION
**Pull request by prateekbh**
Fixes #795 

**What kind of change does this PR introduce?**
Fixes duplicate preact problem.

- Uses `preact` . and `preact-render-to-string` from user land.
- Fall back to local `preact-render-to-string` to local copy but wont work with preact-X
- **Note:** After this we need to include `preact-render-to-string` in all our template's `package.json`

**Did you add tests for your changes?**
Already exist

**Does this PR introduce a breaking change?**
No

### CODE REVIEW

**Comment by hassanbazzi** [comment]
Maybe we should add a note on that somewhere in the FAQ maybe? or Readme?

**Comment by prateekbh** [comment]
about the comments i added?

**Comment by hassanbazzi** [comment]
Well..... For users. I think users will expect the user-land preact to affect pre-rendering Preact.

**Comment by prateekbh** [comment]
**Note:** I really wanted both bundle and `pre-rendering.js` to use preact from user land but sadly doesn't work that way. Can anyone help tell me why

// @marvinhagemeister

**Comment by prateekbh** [comment]
@hassanbazzi I updated the PR to use modules from user land instead its just that it has an added step of installing `preact-render-to-string` in user land

File: packages/cli/lib/lib/webpack/prerender.js [hunk 1]
```diff
@@ -24,10 +24,15 @@ module.exports = function(env, params) {
...
-
+		const { cwd } = env;
+		const preactPath = require.resolve(`${cwd}/node_modules/preact`);
+		const renderToStringPath = require.resolve(
+			`${cwd}/node_modules/preact-render-to-string`
+		);
+		let preact = require(preactPath),
+			renderToString = require(existsSync(renderToStringPath)
+				? renderToStringPath
+				: 'preact-render-to-string');
```
Comment (ForsakenHarmony) [inline packages/cli/lib/lib/webpack/prerender.js]: kinda wondering if we actually need this, it should already resolve from cwd?

and we don't have it as a fixed dep anymore https://github.com/developit/preact-cli/blob/master/packages/cli/package.json#L64-L67

Comment (prateekbh) [reply packages/cli/lib/lib/webpack/prerender.js]: preact/preact-render-to-string both should be used from same source otherwise `__hooks` fail.

Thats why we need to force require this from user land. This will allow user to have the flexibility of using any version of preact/render-to-string they want.

If they don't have, then we can fallback to `cwd` but any usage of hooks will fail.

This'll make it less of a breaking change for everyone as the old ones continue to work as is and the new one will install one more dep and can use hooks

Comment (ForsakenHarmony) [reply packages/cli/lib/lib/webpack/prerender.js]: yeah I'm saying it should only exist in user land either way

Comment (prateekbh) [reply packages/cli/lib/lib/webpack/prerender.js]: that breaks old users, no? just trying to minimize the breaking change impact

Comment (ForsakenHarmony) [reply packages/cli/lib/lib/webpack/prerender.js]: it's already this way for cli v3

Comment (prateekbh) [reply packages/cli/lib/lib/webpack/prerender.js]: well... its also not used anymore.. so ummm makes sense, will make the change

Comment (ForsakenHarmony) [reply packages/cli/lib/lib/webpack/prerender.js]: I meant we shouldn't need the `${cwd}` part? or am I wrong?

Comment (prateekbh) [reply packages/cli/lib/lib/webpack/prerender.js]: we actually do need ${cwd}. Otherwise it uses `preact/render-to-string` from preact-cli's `node_modules` folder instead of the created app's folder

Comment (prateekbh) [reply packages/cli/lib/lib/webpack/prerender.js]: Also `${cwd}` points to the working directory of the created project and not the where `preact-cli` is installed globally.

Comment (ForsakenHarmony) [reply packages/cli/lib/lib/webpack/prerender.js]: well `preact-cli` doesn't have them anymore

but yes it could get in the way if you're not using it via an npm script and or it's just installed globally

Comment (prateekbh) [reply packages/cli/lib/lib/webpack/prerender.js]: Oh sorry for not conveying that.. in my head everyone uses it like that.

Anyways, i'll fix the test

Comment (ForsakenHarmony) [reply packages/cli/lib/lib/webpack/prerender.js]: yeah I kinda assumed having it locally installed, you'll want that for automated builds either way

File: packages/cli/lib/lib/webpack/prerender.js [hunk 2]
```diff
@@ -24,10 +24,11 @@ module.exports = function(env, params) {
 			);
 			return '';
 		}
-
-		let preact = require('preact'),
-			renderToString = require('preact-render-to-string');
-
+		const { cwd } = env;
+		let preact = require(require.resolve(`${cwd}/node_modules/preact`)),
```
Comment (ForsakenHarmony) [inline packages/cli/lib/lib/webpack/prerender.js]:
```suggestion
		const preact = require(require.resolve(`${cwd}/node_modules/preact`));
```

File: packages/cli/lib/lib/webpack/prerender.js [hunk 3]
```diff
@@ -24,10 +24,11 @@ module.exports = function(env, params) {
...
+			renderToString = require(require.resolve(
```
Comment (ForsakenHarmony) [inline packages/cli/lib/lib/webpack/prerender.js]:
```suggestion
		const renderToString = require(require.resolve(
```

File: packages/cli/lib/lib/webpack/prerender.js [hunk 4]
```diff
@@ -24,10 +24,11 @@ module.exports = function(env, params) {
...
+				`${cwd}/node_modules/preact-render-to-string`
+			));
```
Comment (ForsakenHarmony) [inline packages/cli/lib/lib/webpack/prerender.js]:
```suggestion
			));
			
```

**Comment by ForsakenHarmony** [comment]
Not entirely sure how to write a test for it

**Comment by prateekbh** [comment]
:| this was breaking the current tests....
i'll add the fix for tests ASAP

**Comment by ForsakenHarmony** [comment]
I already have it

File: packages/cli/lib/lib/webpack/prerender.js [hunk 5]
```diff
@@ -24,9 +24,12 @@ module.exports = function(env, params) {
 			);
 			return '';
 		}
+		const { cwd } = env;
 
-		let preact = require('preact'),
-			renderToString = require('preact-render-to-string');
+		const preact = require(require.resolve(`${cwd}/node_modules/preact`));
```
Comment (tomsiwik) [inline packages/cli/lib/lib/webpack/prerender.js]: Currently, using a monorepo manager like lerna this workaround breaks the build process and returns:

`✖ ERROR Template execution failed: Error: Cannot find module './node_modules/preact'`

The `cwd` is located inside `root/packages/mypack` and is looking for a `root/packages/mypack/node_modules`, which however is located in `root/node_modules`. Node won't resolve correctly thanks to lerna and thus this will break.

I reverted the changes and logged destination. A revert worked but I think changing the destination to: `${__dirname}/../../../../preact` and `${__dirname}/../../../../preact-render-to-string` would work too.

Comment (alexjsdev) [reply packages/cli/lib/lib/webpack/prerender.js:29]: is there any workaround for this? I just moved a preact app into my monorepo to not have to maintain it in a separate repo, and I'm running into this exact error.

Comment (tomsiwik) [reply packages/cli/lib/lib/webpack/prerender.js:29]: With Lerna and Yarn workspaces no. If you disable yarn workspaces this should work with Lerna though.

Comment (merceyz) [reply packages/cli/lib/lib/webpack/prerender.js:29]: Fixed in https://github.com/preactjs/preact-cli/pull/1418
