### PR TITLE
Fix/port config precedence

### LINKED ISSUE #1596: $PORT preferred over --port
**What is the current behaviour?**

If I type:
```
▶ PORT=7777 preact watch -p 9999
```
it starts on port :7777. Not :9999

```
Compiled successfully!

You can view the application in browser.

Local:            http://0.0.0.0:7777
On Your Network:  http://192.168.1.192:7777
```

**Steps to Reproduce**
Hopefully clear from the description above. 

**What is the expected behaviour?**
I would expect the `-p` option to trump the environment variable. 
Typing `PORT=7777 preact watch -p 9999` is absurd but typing `preact watch -p 9999` is not and then you get negatively surprised that :9999 did not become the port. 

**Please mention any other relevant information**
My use case was that I was using [`foreman`](https://www.npmjs.com/package/foreman) to start a bunch of things, including `preact watch` and for some reason it sets `$PORT=5000` in there. I don't know why and nor is it very relevant.

Is it just me? I feel like the `-p` (or `--port`) is a lot more explicit and should be trumped over the environment variable.

### PR DESCRIPTION
**Pull request by rschristian**
**What kind of change does this PR introduce?**

Refactor to config precedence

**Did you add tests for your changes?**

Yes

**Summary**

Closes #1596

Determining the port is a tad different now:

`--port` -> `$PORT` -> `8080` -> `<random>`

Far left is preferred, far right is the fall back.

The other change is that if a user explicitly selects a port with `-p/--port` that is already taken, we throw an error and exit. That scenario is almost certainly a mistake, either in something running on a port it shouldn't or the wrong port passed to preact-cli. We will continue to fall back to random if `$PORT` is already set and already in use, with the idea being that it's probably another service setting and using that value.

I believe this makes a bit more sense, though could just be my opinion. Let me know!

**Does this PR introduce a breaking change?**

No

### CODE REVIEW

File: packages/cli/lib/util.js [hunk 1]
```diff
@@ -54,3 +55,26 @@ exports.normalizeTemplatesResponse = function (repos = []) {
...
+			const server = net.createServer();
+			server.unref();
+			server.on('error', reject);
+			server.listen({ port }, () => {
+				server.close(resolve);
+			});
+		});
+		return true;
+	} catch (err) {
+		if (err.code !== 'EADDRINUSE') throw err;
```
Comment (ForsakenHarmony) [inline packages/cli/lib/util.js:77]: this works cross platform?

**Review by ForsakenHarmony — APPROVED** [review]

File: packages/cli/lib/util.js (hunk 1 above)
Comment (rschristian) [reply packages/cli/lib/util.js:77]: Should be. [Node's `server.listen()` docs](https://nodejs.org/api/net.html#serverlisten) list it as a common thing to check for, which would be odd if it wasn't cross platform.

I was under the impression that Node's error codes were all cross platform anyways. The docs don't seem to list anything on [this page](https://nodejs.org/api/errors.html#common-system-errors), (common system error or no), as being platform-specific. Could be wrong though?

Comment (rschristian) [reply packages/cli/lib/util.js:77]: Found a random [StackOverflow question of someone getting it on Windows](https://stackoverflow.com/questions/41716833/getting-an-error-listen-eaddrinuse-3000-on-windows-machine/41717870), which I imagine would be the problem child if there was one.

Should be fine to check for that.
