### PR TITLE
fix: disable load manifest in dev

### LINKED ISSUE #1710: Reloading error sometimes
I'm not sure if this is a bug with hot reloading or not, but sometimes I'm getting the following error (happens a lot when I make some larger code changes).

```
 Build  [=============       ] 65% (19.3s) building<i> [webpack-dev-middleware] wait until bundle finished: /backtester
 Build  [==================  ] 90% (37.8s) additional chunk assets processing<e> [webpack-dev-middleware] TypeError: Cannot read property '_value' of undefined
<e>     at module.exports (/home/drager/development/tinker/tinker-web-app/node_modules/preact-cli/lib/lib/webpack/create-load-manifest.js:10:52)
<e>     at /home/drager/development/tinker/tinker-web-app/node_modules/preact-cli/lib/lib/webpack/push-manifest.js:12:22
<e>     at _next1 (eval at create (/home/drager/development/tinker/tinker-web-app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
<e>     at eval (eval at create (/home/drager/development/tinker/tinker-web-app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:51:1)
<e>     at emit (/home/drager/development/tinker/tinker-web-app/node_modules/fork-ts-checker-webpack-plugin/lib/index.js:274:17)
<e>     at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/drager/development/tinker/tinker-web-app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:47:1)
<e>     at Compiler.emitAssets (/home/drager/development/tinker/tinker-web-app/node_modules/webpack/lib/Compiler.js:491:19)
<e>     at onCompiled (/home/drager/development/tinker/tinker-web-app/node_modules/webpack/lib/Watching.js:51:19)
<e>     at /home/drager/development/tinkertinker-web-app/node_modules/webpack/lib/Compiler.js:681:15
<e>     at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/drager/development/tinker/tinker-web-app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
<e>     at /home/drager/development/tinker/tinker-web-app/node_modules/webpack/lib/Compiler.js:678:31
<e>     at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/drager/development/tinker/tinker-web-app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
<e>     at AsyncSeriesHook.lazyCompileHook (/home/drager/development/tinker/tinker-web-app/node_modules/tapable/lib/Hook.js:154:20)
<e>     at /home/drager/development/tinker/tinker-web-app/node_modules/webpack/lib/Compilation.js:1423:35
<e>     at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/drager/development/tinker/tinker-web-app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
<e>     at AsyncSeriesHook.lazyCompileHook (/home/drager/development/tinker/tinker-web-app/node_modules/tapable/lib/Hook.js:154:20)
```

```
Environment Info:
  System:
    OS: Linux 5.3 Ubuntu 18.04.6 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz
  Binaries:
    Node: 16.4.0 - ~/.nvm/versions/node/v16.4.0/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.4.0/bin/yarn
    npm: 7.18.1 - ~/.nvm/versions/node/v16.4.0/bin/npm
  Browsers:
    Chrome: 103.0.5060.114
    Firefox: 102.0
  npmPackages:
    preact: ^10.3.1 => 10.9.0 
    preact-cli: ^3.4.0 => 3.4.0 
    preact-render-to-string: ^5.1.4 => 5.2.0 
    preact-router: ^4.0.1 => 4.0.1 
```

### PR DESCRIPTION
**Pull request by rschristian**
**What kind of change does this PR introduce?**

bugfixes

**Did you add tests for your changes?**

Existing cover

**Summary**

Closes #1710

Looks like there's a race condition in the generation of the load manifest, where the asset manifest isn't guaranteed to exist yet. It's only been reproduced w/ HMR enabled, so that may be the key factor.

Regardless, this is only used to form preload tags, which is never done in dev. Therefore we can just skip the plugin outside of prod.

**Does this PR introduce a breaking change?**

I can't imagine anyone is consuming the load manifest themselves in dev, no. It's possible, but would be pretty weird and not really useful.

### CODE REVIEW

File: packages/cli/lib/lib/webpack/webpack-client-config.js [hunk 1]
```diff
@@ -146,7 +146,7 @@ async function clientConfig(env) {
 				'process.env.ADD_SW': env.sw,
 				'process.env.PRERENDER': env.prerender,
 			}),
-			new PushManifestPlugin(),
+			new PushManifestPlugin(env.isProd),
```
Comment (rschristian) [inline packages/cli/lib/lib/webpack/webpack-client-config.js:149]: Moving this into the prod config seems like a better move at first glance, but `renderHTMLPLugin` depends on it being ran first so we need to keep it here.

**Review by ForsakenHarmony — APPROVED** [review]
