### PR TITLE
fix: do not prompt on supplying template as an argument.

### LINKED ISSUE #1523: Ambiguities with create command usage
**Do you want to request a _feature_ or report a _bug_?**
This proposal aims at changing the current behavior of the `create` command.

**What is the current behaviour?**
As specified in the [docs](https://github.com/preactjs/preact-cli#preact-create), the `create` command expects the `template-name` and `project-name` (required arguments). However, the current implementation treats them as optional arguments.
https://github.com/preactjs/preact-cli/blob/4acc8c7768936cd128998971e0e6d7425cd5c204/packages/cli/lib/index.js#L44

**If the current behaviour is a bug, please provide the steps to reproduce.**
```sh
$ preact create default
```

https://github.com/preactjs/preact-cli/blob/4acc8c7768936cd128998971e0e6d7425cd5c204/packages/cli/lib/commands/create.js#L209-L214

The current implementation checks for a `--template` flag, which doesn't exist, The prompt to choose a `preactjs-template` show up even though it is specified.

https://github.com/preactjs/preact-cli/blob/4acc8c7768936cd128998971e0e6d7425cd5c204/packages/cli/lib/commands/create.js#L81-L87

**What is the expected behaviour?**
```sh
preact create [project-name] [options]
```
- It would be better to add a `--template` flag.
- The `--name` flag is not required.

**Please mention other relevant information.**
N/A

### PR DESCRIPTION
**Pull request by jamesgeorge007**
**What kind of change does this PR introduce?**
patch

**Did you add tests for your changes?**
Nope

**Summary**
Supplying the `preactjs-template` as an argument doesn't show the respective prompt.

#1523 

**Does this PR introduce a breaking change?**
Nope

**Other information**
N/A

### CODE REVIEW

**Comment by rschristian** [comment]
Definitely don't think we want to deprecate anything here. This would also be a major, not a minor, as all deprecations are.

We just need to clean up the ambiguity/consistency between the docs and actual commands while also fixing that issue with the flag not existing. I don't think there's any need to break the existing behavior like this.

File: packages/cli/lib/commands/create.js [hunk 1]
```diff
@@ -78,11 +78,16 @@ const options = [
...
 
 	return [
 		// Required data
+		{
+			type: name ? null : 'text',
+			name: 'name',
+			message: 'The name of your application',
+		},
 		{
 			type: argv.template ? null : 'select',
```
Comment (rschristian) [inline packages/cli/lib/commands/create.js:87]: You could just swap this flag for `repo` from `create()` and the issue would be resolved.

Comment (jamesgeorge007) [reply packages/cli/lib/commands/create.js:87]: The intended way to supply additional arguments to a subcommand would be along with the flags that denote their purpose.
```diff
- preact create [template-name] [project-name]
+ preact create [name] --template [template-name]
```

```sh
preact create [name] [options]
```

It would be better to have a `--template` flag in that regard. Nevertheless, I would be happy to address the current issue if the proposed change is not intentional.

Comment (rschristian) [reply packages/cli/lib/commands/create.js:87]: Sure, but I don't think the template is an "additional" argument. It's required; we just also have a way to catch users if they forget it. 

Regardless, a major, as this currently is, will likely be a long ways away. Better to just fix up the behavior now.

File: packages/cli/lib/commands/create.js [hunk 2]
```diff
@@ -78,13 +78,13 @@ const options = [
 ];
 
 // Formulate Questions if `create` args are missing
-function requestParams(argv, templates) {
+function requestParams(repo, dest, argv, templates) {
```
Comment (rschristian) [inline packages/cli/lib/commands/create.js:81]: Is there a reason to drag in `dest` too?

**Comment by rschristian** [comment]
I do agree with your original work and I think it's something we should look into, getting all of the commands a bit more consistent. It was just that a breaking change is so far away from being merge-able in all likelihood that it wouldn't solve the immediate issue of the flag not existing.

I might end up copying your original commit over to a more long term PR where the API of the CLI can be more properly considered.

File: packages/cli/lib/commands/create.js (hunk 2 above)
Comment (jamesgeorge007) [reply packages/cli/lib/commands/create.js:81]: https://github.com/preactjs/preact-cli/blob/0ccce89fc2ed6e9367d5889f9c16f2f3cd89f988/packages/cli/lib/commands/create.js#L99

There isn't a `--dest` flag.

Comment (rschristian) [reply packages/cli/lib/commands/create.js:81]: Whoops, totally right. Forgot we used 'name' instead.

**Review by rschristian — APPROVED** [review]
LGTM
